### ISSUE TITLE
To-do: cherry-pick mrpt-1.5 => master

### ISSUE THREAD

**Issue by jlblancoc** [MRPT/mrpt#831]
List: 
* [x] a6d5d55e4d7daa869b8b84f3f5428d90aeb019d5
* [x] e40b772157749cffd3332877d0f3f92aaf2cbfab
* [x] c6f5aca0d9c3dd2c31435ff1dcb851de6e004312
* [x] 8cda29547968f5a8bd8ab91ced52ade3f5369538
